// <auto-generated />
using System;
using Csd.Comisiones.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Csd.Comisiones.Persistence.Migrations
{
    [DbContext(typeof(ComisionesDbContext))]
    [Migration("20260416165755_MotivoSolicitud_Migration")]
    partial class MotivoSolicitud_Migration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Csd.Comisiones.Domain.Entities.Area", b =>
                {
                    b.Property<int>("AreaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AreaId"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("CreadoPor")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("datetime");

                    b.Property<string>("ModificadoPor")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("AreaId");

                    b.HasIndex("Nombre")
                        .IsUnique();

                    b.ToTable("Area", (string)null);
                });

            modelBuilder.Entity("Csd.Comisiones.Domain.Entities.Autorizador", b =>
                {
                    b.Property<int>("AutorizadorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AutorizadorId"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("CreadoPor")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("EmpleadoId")
                        .HasColumnType("int");

                    b.Property<bool>("EsAlterno")
                        .HasColumnType("bit");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("datetime");

                    b.Property<string>("ModificadoPor")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Nivel")
                        .HasColumnType("int");

                    b.Property<int>("ObraId")
                        .HasColumnType("int");

                    b.HasKey("AutorizadorId");

                    b.HasIndex("EmpleadoId");

                    b.HasIndex("ObraId");

                    b.ToTable("Autorizador", (string)null);
                });

            modelBuilder.Entity("Csd.Comisiones.Domain.Entities.Ciudad", b =>
                {
                    b.Property<int>("CiudadId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CiudadId"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("CreadoPor")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("datetime");

                    b.Property<string>("ModificadoPor")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("CiudadId");

                    b.HasIndex("Nombre")
                        .IsUnique();

                    b.ToTable("Ciudad", (string)null);
                });

            modelBuilder.Entity("Csd.Comisiones.Domain.Entities.Empleado", b =>
                {
                    b.Property<int>("EmpleadoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EmpleadoId"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<int>("AreaId")
                        .HasColumnType("int");

                    b.Property<string>("Correo")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("CreadoPor")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("datetime");

                    b.Property<string>("ModificadoPor")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("NombreCompleto")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("NumeroEmpleado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("EmpleadoId");

                    b.HasIndex("AreaId");

                    b.HasIndex("NumeroEmpleado")
                        .IsUnique();

                    b.ToTable("Empleado", (string)null);
                });

            modelBuilder.Entity("Csd.Comisiones.Domain.Entities.EstatusDetalle", b =>
                {
                    b.Property<int>("EstatusDetalleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EstatusDetalleId"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("CreadoPor")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("datetime");

                    b.Property<string>("ModificadoPor")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("EstatusDetalleId");

                    b.HasIndex("Nombre")
                        .IsUnique();

                    b.ToTable("EstatusDetalle", (string)null);
                });

            modelBuilder.Entity("Csd.Comisiones.Domain.Entities.EstatusSolicitud", b =>
                {
                    b.Property<int>("EstatusSolicitudId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EstatusSolicitudId"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("CreadoPor")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("datetime");

                    b.Property<string>("ModificadoPor")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("EstatusSolicitudId");

                    b.ToTable("EstatusSolicitud", (string)null);
                });

            modelBuilder.Entity("Csd.Comisiones.Domain.Entities.MotivoSolicitud", b =>
                {
                    b.Property<int>("MotivoSolicitudId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MotivoSolicitudId"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("CreadoPor")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("datetime");

                    b.Property<string>("ModificadoPor")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("MotivoSolicitudId");

                    b.HasIndex("Nombre")
                        .IsUnique();

                    b.ToTable("MotivoSolicitud", (string)null);
                });

            modelBuilder.Entity("Csd.Comisiones.Domain.Entities.Obra", b =>
                {
                    b.Property<int>("ObraId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ObraId"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("CreadoPor")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmpresaId")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("datetime");

                    b.Property<string>("ModificadoPor")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("ObraId");

                    b.HasIndex("Nombre")
                        .IsUnique();

                    b.ToTable("Obra", (string)null);
                });

            modelBuilder.Entity("Csd.Comisiones.Domain.Entities.Proveedor", b =>
                {
                    b.Property<int>("ProveedorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProveedorId"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<int>("CiudadId")
                        .HasColumnType("int");

                    b.Property<string>("Correo")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("CreadoPor")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("datetime");

                    b.Property<string>("ModificadoPor")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("ProporcionaAlimentos")
                        .HasColumnType("bit");

                    b.Property<bool>("ProporcionaHospedaje")
                        .HasColumnType("bit");

                    b.Property<int>("TipoProveedor")
                        .HasColumnType("int");

                    b.HasKey("ProveedorId");

                    b.HasIndex("CiudadId");

                    b.HasIndex("Nombre", "CiudadId")
                        .IsUnique();

                    b.ToTable("Proveedor", (string)null);
                });

            modelBuilder.Entity("Csd.Comisiones.Domain.Entities.ProveedorServicio", b =>
                {
                    b.Property<int>("ProveedorServicioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProveedorServicioId"));

                    b.Property<string>("CreadoPor")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("datetime");

                    b.Property<string>("ModificadoPor")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Precio")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("ProveedorId")
                        .HasColumnType("int");

                    b.Property<int>("TipoServicio")
                        .HasColumnType("int");

                    b.HasKey("ProveedorServicioId");

                    b.HasIndex("ProveedorId");

                    b.ToTable("ProveedorServicio", (string)null);
                });

            modelBuilder.Entity("Csd.Comisiones.Domain.Entities.Solicitud", b =>
                {
                    b.Property<int>("SolicitudId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SolicitudId"));

                    b.Property<int>("AreaId")
                        .HasColumnType("int");

                    b.Property<int?>("CiudadId")
                        .HasColumnType("int");

                    b.Property<string>("Comentarios")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("CreadoPor")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("EstatusSolicitudId")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("FechaFin")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaInicio")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("datetime");

                    b.Property<string>("Folio")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ModificadoPor")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("MotivoSolicitudId")
                        .HasColumnType("int");

                    b.Property<int>("ObraId")
                        .HasColumnType("int");

                    b.Property<int>("SolicitanteId")
                        .HasColumnType("int");

                    b.HasKey("SolicitudId");

                    b.HasIndex("AreaId");

                    b.HasIndex("CiudadId");

                    b.HasIndex("EstatusSolicitudId");

                    b.HasIndex("MotivoSolicitudId");

                    b.HasIndex("ObraId");

                    b.ToTable("Solicitud", (string)null);
                });

            modelBuilder.Entity("Csd.Comisiones.Domain.Entities.SolicitudAutorizacion", b =>
                {
                    b.Property<int>("SolicitudAutorizacionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SolicitudAutorizacionId"));

                    b.Property<int>("AutorizadorId")
                        .HasColumnType("int");

                    b.Property<string>("Comentarios")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("CreadoPor")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("EstatusAutorizacionId")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("FechaRespuesta")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModificadoPor")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("SolicitudId")
                        .HasColumnType("int");

                    b.HasKey("SolicitudAutorizacionId");

                    b.HasIndex("AutorizadorId");

                    b.HasIndex("SolicitudId");

                    b.ToTable("SolicitudAutorizacion", (string)null);
                });

            modelBuilder.Entity("Csd.Comisiones.Domain.Entities.SolicitudComida", b =>
                {
                    b.Property<int>("SolicitudComidaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SolicitudComidaId"));

                    b.Property<string>("CreadoPor")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("EstatusDetalleId")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("FechaFin")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaInicio")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("datetime");

                    b.Property<string>("ModificadoPor")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("PrecioUnitario")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int?>("ProveedorId")
                        .HasColumnType("int");

                    b.Property<int>("SolicitudEmpleadoId")
                        .HasColumnType("int");

                    b.Property<int>("TipoComidaId")
                        .HasColumnType("int");

                    b.Property<int>("UbicacionAlimentoId")
                        .HasColumnType("int");

                    b.HasKey("SolicitudComidaId");

                    b.HasIndex("EstatusDetalleId");

                    b.HasIndex("ProveedorId");

                    b.HasIndex("SolicitudEmpleadoId");

                    b.HasIndex("TipoComidaId");

                    b.HasIndex("UbicacionAlimentoId");

                    b.ToTable("SolicitudComida", (string)null);
                });

            modelBuilder.Entity("Csd.Comisiones.Domain.Entities.SolicitudEmpleado", b =>
                {
                    b.Property<int>("SolicitudEmpleadoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SolicitudEmpleadoId"));

                    b.Property<string>("CreadoPor")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("EmpleadoId")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("FechaFin")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaInicio")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("datetime");

                    b.Property<string>("ModificadoPor")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal?>("MontoPago")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("SolicitudId")
                        .HasColumnType("int");

                    b.Property<int>("TipoAsignacion")
                        .HasColumnType("int");

                    b.HasKey("SolicitudEmpleadoId");

                    b.HasIndex("EmpleadoId");

                    b.HasIndex("SolicitudId");

                    b.ToTable("SolicitudEmpleado", (string)null);
                });

            modelBuilder.Entity("Csd.Comisiones.Domain.Entities.SolicitudHotel", b =>
                {
                    b.Property<int>("SolicitudHotelId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SolicitudHotelId"));

                    b.Property<string>("CreadoPor")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("EstatusDetalleId")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("FechaFin")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaInicio")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("datetime");

                    b.Property<string>("ModificadoPor")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("PrecioUnitario")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int?>("ProveedorId")
                        .HasColumnType("int");

                    b.Property<int>("SolicitudEmpleadoId")
                        .HasColumnType("int");

                    b.Property<int>("TipoHabitacionId")
                        .HasColumnType("int");

                    b.HasKey("SolicitudHotelId");

                    b.HasIndex("EstatusDetalleId");

                    b.HasIndex("ProveedorId");

                    b.HasIndex("SolicitudEmpleadoId");

                    b.HasIndex("TipoHabitacionId");

                    b.ToTable("SolicitudHotel", (string)null);
                });

            modelBuilder.Entity("Csd.Comisiones.Domain.Entities.SolicitudSeguimiento", b =>
                {
                    b.Property<int>("SolicitudSeguimientoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SolicitudSeguimientoId"));

                    b.Property<string>("Comentarios")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("CreadoPor")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("EstatusSolicitudId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("datetime");

                    b.Property<string>("ModificadoPor")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("SolicitudId")
                        .HasColumnType("int");

                    b.HasKey("SolicitudSeguimientoId");

                    b.HasIndex("EstatusSolicitudId");

                    b.HasIndex("SolicitudId");

                    b.ToTable("SolicitudSeguimiento", (string)null);
                });

            modelBuilder.Entity("Csd.Comisiones.Domain.Entities.TipoComida", b =>
                {
                    b.Property<int>("TipoComidaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TipoComidaId"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("CreadoPor")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("datetime");

                    b.Property<string>("ModificadoPor")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("TipoComidaId");

                    b.HasIndex("Nombre")
                        .IsUnique();

                    b.ToTable("TipoComida", (string)null);
                });

            modelBuilder.Entity("Csd.Comisiones.Domain.Entities.TipoHabitacion", b =>
                {
                    b.Property<int>("TipoHabitacionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TipoHabitacionId"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("CreadoPor")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("datetime");

                    b.Property<string>("ModificadoPor")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("TipoHabitacionId");

                    b.HasIndex("Nombre")
                        .IsUnique();

                    b.ToTable("TipoHabitacion", (string)null);
                });

            modelBuilder.Entity("Csd.Comisiones.Domain.Entities.UbicacionAlimento", b =>
                {
                    b.Property<int>("UbicacionAlimentoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UbicacionAlimentoId"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("CreadoPor")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("datetime");

                    b.Property<string>("ModificadoPor")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("UbicacionAlimentoId");

                    b.HasIndex("Nombre")
                        .IsUnique();

                    b.ToTable("UbicacionAlimento", (string)null);
                });

            modelBuilder.Entity("Csd.Comisiones.Domain.Entities.Autorizador", b =>
                {
                    b.HasOne("Csd.Comisiones.Domain.Entities.Empleado", null)
                        .WithMany()
                        .HasForeignKey("EmpleadoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Csd.Comisiones.Domain.Entities.Obra", null)
                        .WithMany()
                        .HasForeignKey("ObraId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Csd.Comisiones.Domain.Entities.Proveedor", b =>
                {
                    b.HasOne("Csd.Comisiones.Domain.Entities.Ciudad", null)
                        .WithMany()
                        .HasForeignKey("CiudadId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Csd.Comisiones.Domain.Entities.ProveedorServicio", b =>
                {
                    b.HasOne("Csd.Comisiones.Domain.Entities.Proveedor", "Proveedor")
                        .WithMany("Servicios")
                        .HasForeignKey("ProveedorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Proveedor");
                });

            modelBuilder.Entity("Csd.Comisiones.Domain.Entities.Solicitud", b =>
                {
                    b.HasOne("Csd.Comisiones.Domain.Entities.Area", "Area")
                        .WithMany()
                        .HasForeignKey("AreaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Csd.Comisiones.Domain.Entities.Ciudad", "Ciudad")
                        .WithMany()
                        .HasForeignKey("CiudadId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Csd.Comisiones.Domain.Entities.EstatusSolicitud", "Estatus")
                        .WithMany()
                        .HasForeignKey("EstatusSolicitudId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Csd.Comisiones.Domain.Entities.MotivoSolicitud", "MotivoSolicitud")
                        .WithMany()
                        .HasForeignKey("MotivoSolicitudId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Csd.Comisiones.Domain.Entities.Obra", "Obra")
                        .WithMany()
                        .HasForeignKey("ObraId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Area");

                    b.Navigation("Ciudad");

                    b.Navigation("Estatus");

                    b.Navigation("MotivoSolicitud");

                    b.Navigation("Obra");
                });

            modelBuilder.Entity("Csd.Comisiones.Domain.Entities.SolicitudAutorizacion", b =>
                {
                    b.HasOne("Csd.Comisiones.Domain.Entities.Autorizador", "Autorizador")
                        .WithMany("Autorizaciones")
                        .HasForeignKey("AutorizadorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Csd.Comisiones.Domain.Entities.Solicitud", "Solicitud")
                        .WithMany("Autorizaciones")
                        .HasForeignKey("SolicitudId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Autorizador");

                    b.Navigation("Solicitud");
                });

            modelBuilder.Entity("Csd.Comisiones.Domain.Entities.SolicitudComida", b =>
                {
                    b.HasOne("Csd.Comisiones.Domain.Entities.EstatusDetalle", "EstatusDetalle")
                        .WithMany()
                        .HasForeignKey("EstatusDetalleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Csd.Comisiones.Domain.Entities.Proveedor", "Proveedor")
                        .WithMany()
                        .HasForeignKey("ProveedorId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Csd.Comisiones.Domain.Entities.SolicitudEmpleado", "SolicitudEmpleado")
                        .WithMany("Comidas")
                        .HasForeignKey("SolicitudEmpleadoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Csd.Comisiones.Domain.Entities.TipoComida", "TipoComida")
                        .WithMany()
                        .HasForeignKey("TipoComidaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Csd.Comisiones.Domain.Entities.UbicacionAlimento", null)
                        .WithMany()
                        .HasForeignKey("UbicacionAlimentoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("EstatusDetalle");

                    b.Navigation("Proveedor");

                    b.Navigation("SolicitudEmpleado");

                    b.Navigation("TipoComida");
                });

            modelBuilder.Entity("Csd.Comisiones.Domain.Entities.SolicitudEmpleado", b =>
                {
                    b.HasOne("Csd.Comisiones.Domain.Entities.Empleado", "Empleado")
                        .WithMany()
                        .HasForeignKey("EmpleadoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Csd.Comisiones.Domain.Entities.Solicitud", "Solicitud")
                        .WithMany("Empleados")
                        .HasForeignKey("SolicitudId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Empleado");

                    b.Navigation("Solicitud");
                });

            modelBuilder.Entity("Csd.Comisiones.Domain.Entities.SolicitudHotel", b =>
                {
                    b.HasOne("Csd.Comisiones.Domain.Entities.EstatusDetalle", "EstatusDetalle")
                        .WithMany()
                        .HasForeignKey("EstatusDetalleId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Csd.Comisiones.Domain.Entities.Proveedor", "Proveedor")
                        .WithMany()
                        .HasForeignKey("ProveedorId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Csd.Comisiones.Domain.Entities.SolicitudEmpleado", "SolicitudEmpleado")
                        .WithMany("Hoteles")
                        .HasForeignKey("SolicitudEmpleadoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Csd.Comisiones.Domain.Entities.TipoHabitacion", null)
                        .WithMany()
                        .HasForeignKey("TipoHabitacionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("EstatusDetalle");

                    b.Navigation("Proveedor");

                    b.Navigation("SolicitudEmpleado");
                });

            modelBuilder.Entity("Csd.Comisiones.Domain.Entities.SolicitudSeguimiento", b =>
                {
                    b.HasOne("Csd.Comisiones.Domain.Entities.EstatusSolicitud", "Estatus")
                        .WithMany()
                        .HasForeignKey("EstatusSolicitudId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Csd.Comisiones.Domain.Entities.Solicitud", "Solicitud")
                        .WithMany("Seguimientos")
                        .HasForeignKey("SolicitudId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Estatus");

                    b.Navigation("Solicitud");
                });

            modelBuilder.Entity("Csd.Comisiones.Domain.Entities.Autorizador", b =>
                {
                    b.Navigation("Autorizaciones");
                });

            modelBuilder.Entity("Csd.Comisiones.Domain.Entities.Proveedor", b =>
                {
                    b.Navigation("Servicios");
                });

            modelBuilder.Entity("Csd.Comisiones.Domain.Entities.Solicitud", b =>
                {
                    b.Navigation("Autorizaciones");

                    b.Navigation("Empleados");

                    b.Navigation("Seguimientos");
                });

            modelBuilder.Entity("Csd.Comisiones.Domain.Entities.SolicitudEmpleado", b =>
                {
                    b.Navigation("Comidas");

                    b.Navigation("Hoteles");
                });
#pragma warning restore 612, 618
        }
    }
}
